name: kuppifeed

description: A modern, modular Flutter front-end for KuppiFeed.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  google_fonts: ^6.1.0
  supabase_flutter: ^2.0.0
  flutter_dotenv: ^5.1.0
  uuid: ^4.0.0
  shared_preferences: ^2.2.0

  image_picker: ^1.0.0
  permission_handler: ^11.4.0
  bcrypt: ^1.2.0
  gal: ^2.3.2
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/.env
    - assets/Logo.png
    - assets/icon123.png

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon123.png"
  adaptive_icon_background: "#6C63FF"
  adaptive_icon_foreground: "assets/icon123.png"
